// <auto-generated />
using System;
using DataAccessLayer;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DataAccessLayer.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250731204656_InitialCreate19")]
    partial class InitialCreate19
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DataAccessLayer.Models.Client", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DelayDePayment")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("ExnLimite")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("ExnUtiliser")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusTVA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("entityId")
                        .HasColumnType("int");

                    b.Property<string>("identifiantFiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("entityId");

                    b.ToTable("clients");
                });

            modelBuilder.Entity("DataAccessLayer.Models.CompteBancaire", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Agence")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Banque")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateOuverture")
                        .HasColumnType("datetime2");

                    b.Property<string>("Devise")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntiteId")
                        .HasColumnType("int");

                    b.Property<bool>("EstActif")
                        .HasColumnType("bit");

                    b.Property<string>("IBAN")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RIB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("SoldeInitial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SwiftCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntiteId");

                    b.ToTable("compteBancaires");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Entity", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Adress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CNSS")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ICE")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Patent")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("code")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("identifiantfiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.ToTable("Entities");
                });

            modelBuilder.Entity("DataAccessLayer.Models.FactureClient", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("DateEcheance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateEmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeDePayment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontantTH")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TVa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("clientId")
                        .HasColumnType("int");

                    b.Property<string>("devis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("entiteId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("payed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("clientId");

                    b.HasIndex("entiteId");

                    b.ToTable("factureClients");
                });

            modelBuilder.Entity("DataAccessLayer.Models.FactureFournisseur", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("DateEcheance")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DateReception")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ModeDePayment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("MontantTH")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Retenue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TVa")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("devis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("entiteId")
                        .HasColumnType("int");

                    b.Property<int>("fournisseurId")
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("payed")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("id");

                    b.HasIndex("entiteId");

                    b.HasIndex("fournisseurId");

                    b.ToTable("factureFournisseurs");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Fournisseur", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Rib")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StatusTVA")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("TauxDeReturn")
                        .HasColumnType("float");

                    b.Property<int>("delay")
                        .HasColumnType("int");

                    b.Property<int>("entityId")
                        .HasColumnType("int");

                    b.Property<string>("identifiantFiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("id");

                    b.HasIndex("entityId");

                    b.ToTable("fournisseurs");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Payment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("nvarchar(21)");

                    b.Property<bool>("IsAutrePayment")
                        .HasColumnType("bit");

                    b.Property<string>("MethodeDePayment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegisteredById")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("comptebancaireId")
                        .HasColumnType("int");

                    b.Property<int>("entityid")
                        .HasColumnType("int");

                    b.Property<string>("entityname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("registername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredById");

                    b.HasIndex("comptebancaireId");

                    b.HasIndex("entityid");

                    b.ToTable("payments");

                    b.HasDiscriminator().HasValue("Payment");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("DataAccessLayer.Models.PaymentDocument", b =>
                {
                    b.Property<int>("DocumentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DocumentId"));

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PaymentId")
                        .HasColumnType("int");

                    b.Property<int?>("PaymentUtilisatuerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UploadedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("DocumentId");

                    b.HasIndex("PaymentId");

                    b.HasIndex("PaymentUtilisatuerId");

                    b.ToTable("PaymentDocuments");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PaymentUtilisatuer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsAutrePayment")
                        .HasColumnType("bit");

                    b.Property<string>("MethodeDePayment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegisteredById")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UsedById")
                        .HasColumnType("int");

                    b.Property<string>("compte")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("datedefacture")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("debit")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("devis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("entityid")
                        .HasColumnType("int");

                    b.Property<string>("entityname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("months")
                        .HasColumnType("int");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("reference")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("registername")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ville")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("RegisteredById");

                    b.HasIndex("UsedById");

                    b.HasIndex("entityid");

                    b.ToTable("paymentUtilisatuers");
                });

            modelBuilder.Entity("DataAccessLayer.Models.UserSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Annefiscal")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Devis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("IsRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("LastModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("RetenueRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TvaRate")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("UserSettings");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Utilisatuer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PaymentFournisseur", b =>
                {
                    b.HasBaseType("DataAccessLayer.Models.Payment");

                    b.Property<string>("devis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fournisseurFacture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("fournisseurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(18,2)");

                    b.HasDiscriminator().HasValue("PaymentFournisseur");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PaymentParClient", b =>
                {
                    b.HasBaseType("DataAccessLayer.Models.Payment");

                    b.Property<string>("FactureClient")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("clientname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("devis")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("rate")
                        .HasColumnType("decimal(18,2)");

                    b.ToTable("payments", t =>
                        {
                            t.Property("devis")
                                .HasColumnName("PaymentParClient_devis");

                            t.Property("rate")
                                .HasColumnName("PaymentParClient_rate");
                        });

                    b.HasDiscriminator().HasValue("PaymentParClient");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Client", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Entity", "entity")
                        .WithMany("clients")
                        .HasForeignKey("entityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("entity");
                });

            modelBuilder.Entity("DataAccessLayer.Models.CompteBancaire", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Entity", "Entite")
                        .WithMany("compteBancaires")
                        .HasForeignKey("EntiteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Entite");
                });

            modelBuilder.Entity("DataAccessLayer.Models.FactureClient", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Client", "client")
                        .WithMany("FacturesClients")
                        .HasForeignKey("clientId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Entity", "entity")
                        .WithMany("factureClients")
                        .HasForeignKey("entiteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("client");

                    b.Navigation("entity");
                });

            modelBuilder.Entity("DataAccessLayer.Models.FactureFournisseur", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Entity", "entity")
                        .WithMany("factureFournisseurs")
                        .HasForeignKey("entiteId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Fournisseur", "fournisseur")
                        .WithMany("factureFournisseurs")
                        .HasForeignKey("fournisseurId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("entity");

                    b.Navigation("fournisseur");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Fournisseur", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Entity", "entity")
                        .WithMany("fournisseurs")
                        .HasForeignKey("entityId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("entity");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Payment", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Utilisatuer", "RegisteredBy")
                        .WithMany()
                        .HasForeignKey("RegisteredById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.CompteBancaire", "compteBancaire")
                        .WithMany("Payments")
                        .HasForeignKey("comptebancaireId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Entity", "entity")
                        .WithMany()
                        .HasForeignKey("entityid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegisteredBy");

                    b.Navigation("compteBancaire");

                    b.Navigation("entity");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PaymentDocument", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Payment", "Payment")
                        .WithMany("Documents")
                        .HasForeignKey("PaymentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.PaymentUtilisatuer", null)
                        .WithMany("Documents")
                        .HasForeignKey("PaymentUtilisatuerId");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PaymentUtilisatuer", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Utilisatuer", "RegisteredBy")
                        .WithMany()
                        .HasForeignKey("RegisteredById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Utilisatuer", "UsedBy")
                        .WithMany()
                        .HasForeignKey("UsedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DataAccessLayer.Models.Entity", "entity")
                        .WithMany()
                        .HasForeignKey("entityid")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RegisteredBy");

                    b.Navigation("UsedBy");

                    b.Navigation("entity");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Utilisatuer", b =>
                {
                    b.HasOne("DataAccessLayer.Models.Entity", "entity")
                        .WithMany("utilisatuers")
                        .HasForeignKey("EntityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("entity");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Client", b =>
                {
                    b.Navigation("FacturesClients");
                });

            modelBuilder.Entity("DataAccessLayer.Models.CompteBancaire", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Entity", b =>
                {
                    b.Navigation("clients");

                    b.Navigation("compteBancaires");

                    b.Navigation("factureClients");

                    b.Navigation("factureFournisseurs");

                    b.Navigation("fournisseurs");

                    b.Navigation("utilisatuers");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Fournisseur", b =>
                {
                    b.Navigation("factureFournisseurs");
                });

            modelBuilder.Entity("DataAccessLayer.Models.Payment", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("DataAccessLayer.Models.PaymentUtilisatuer", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
